# use ubuntu library image until our works
image: registry.gitlab.com/untrustedhost/docker-in-docker
services:
  - docker:dind
variables:
  DOCKER_HOST: tcp://docker:2375
  DOCKER_DRIVER: overlay2
#  RELEASE_IMAGE:
  GITLAB_RELEASE_IMAGE: registry.gitlab.com/untrustedhost/baseimages/ubuntu

# any non-master branch tries to build an image as a test.
test:
  stage: test
  script:
    - ./build-images.sh
  except:
    - master

# but only master will run signing checks and pushes
# this is flagged as a build stage so it stops the pipeline quickly.
master:
  stage: build
  script:
    - ./.ci/signcheck
  only:
    - master

# duplicated from test, mostly.
deploy:
  stage: deploy
  environment:
    name: deploy
  script:
    - ./build-images.sh
    - ./.ci/publish-docker
  only:
    - master
