# use ubuntu library image until our works
image: ubuntu:18.04
services:
  - docker:dind
variables:
  DOCKER_HOST: tcp://docker:2375
  DOCKER_DRIVER: overlay2

# any branch tries to build an image
test:
  script:
    - ./prereqs.sh
    - ./build-images.sh

# but only master will run signing checks and pushes
master:
  script:
    - apt-get update && apt-get -q -y install git gpg
    - ./.ci/signcheck
  only:
    - master
