# use ubuntu library image until our works
image: registry.gitlab.com/untrustedhost/docker-in-docker
services:
  - docker:19.03.5-dind
variables:
  DOCKER_HOST: tcp://docker:2375
  DOCKER_DRIVER: overlay2
#  RELEASE_IMAGE:
  GITLAB_RELEASE_IMAGE: registry.gitlab.com/untrustedhost/baseimages/ubuntu
  CODEBASE: base

# any non-master branch tries to build an image as a test.
test:
  stage: test
  script:
    - ./build.sh
  except:
    - mainline

# but only master will run signing checks and pushes
# this is flagged as a build stage so it stops the pipeline quickly.
mainline:
  stage: build
  script:
    - /usr/lib/untrustedhost/scripts/gitgpgsign_check
  only:
    - mainline

# duplicated from test, mostly.
deploy:
  stage: deploy
  environment:
    name: deploy
  script:
    - ./build.sh
    - /usr/lib/untrustedhost/scripts/publish-docker
  only:
    - mainline
