image: registry.gitlab.com/untrustedhost/docker-in-docker
services:
  - docker:dind
variables:
  DOCKER_HOST: tcp://docker:2375
  DOCKER_DRIVER: overlay2
# this is...the ubuntu release tag...
  GITLAB_RELEASE_IMAGE: registry.gitlab.com/untrustedhost/baseimages/ubuntu
# and fedora can have it's own. thankfully the release bits don't conflict.
  FEDORA_RELEASE_IMAGE: registry.gitlab.com/untrustedhost/baseimages/fedora
  CODEBASE: base
  DEFAULT_VARIANT: focal
  VARIANTS: bionic focal jammy
  DEFAULT_FEDORA: 36
  FEDORA_VARIANTS: 35 36

# any non-mainline branch tries to build an image as a test.
test:
  stage: test
  script:
    - bash -exc 'for v in $VARIANTS ; do VERSION_CODENAME=$v ./build.sh ; done'
    - bash -exc 'for v in $FEDORA_VARIANTS ; do FEDORA_VER=$v ./build-fedora.sh ; done'
  except:
    - mainline

# but only mainline will run signing checks and pushes
# this is flagged as a build stage so it stops the pipeline quickly.
mainline:
  stage: build
  script:
    - /usr/lib/untrustedhost/scripts/gitgpgsign_check
  only:
    - mainline

# duplicated from test, mostly.
deploy:
  stage: deploy
  environment:
    name: deploy
  script:
    - bash -exc 'for v in $VARIANTS ; do VERSION_CODENAME=$v ./build.sh ; done'
    - bash -exc 'for v in $VARIANTS ; do IMAGESOURCE="build/$v/release" VARIANT="$v" /usr/lib/untrustedhost/scripts/publish-docker ; done'
  only:
    - mainline
