version: 2

jobs:
  build:
    docker:
      - image: docker.palantir.build/circle2-build-images/ubuntu-jdk-npm:0.19.0
    working_directory: ~/project
    environment:
      - CIRCLECI=true
      - DOCKER_SINK=docker.palantir.build/computetools
      - UBUNTU_URI=https://artifactory.palantir.build/artifactory/external-apt-ubuntu-ec2/
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: install prerequisites
          command: sudo apt-get -q update && sudo apt-get -q -yy install debootstrap yum
      - run:
          name: chroot build base images
          command: env FORCE_BUILD=1 ./mkimage-chroot.sh
      - run:
          name: push base images
          command: env ./publish.sh
