version: 2

jobs:
  build:
    docker:
      - image: centos:7
    working_directory: /project
    environment:
      - DOCKER_SINK=docker.palantir.build/computetools
      - UBUNTU_URI=https://artifactory.palantir.build/artifactory/external-apt-ubuntu-ec2/
    steps:
      - checkout
      - run:
          name: install docker prereqs
          command: yum-config-manager --add-repo https://download.docker.com/linux/centos/docker-ce.repo && yum -y install docker-ce && yum -y install epel-release && yum -y install debootstrap perl which dpkg
      - setup_remote_docker
      - run:
          name: chroot build base images
          command: env FORCE_BUILD=1 ./mkimage-chroot.sh
      - run:
          name: push base images
          command: env ./publish.sh
