version: 2

references:
  common_config: &common_config
    docker:
      - image: docker.palantir.build/circle2-build-images/ubuntu-jdk-npm:0.19.0
    working_directory: ~/project
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: install prerequisites
          command: sudo apt-get -q update && sudo apt-get -q -yy install debootstrap yum db-util
      - run:
          name: chroot build base images
          command: env ./mkimage-chroot.sh
      - run:
          name: push base images
          command: env ./publish.sh

jobs:
  build:
    <<: *common_config
    environment:
      - DOCKER_SINK=docker.palantir.build/computetools
      - UBUNTU_URI=https://artifactory.palantir.build/artifactory/external-apt-ubuntu-ec2/
      - FORCE_BUILD=1
  nightly:
    <<: *common_config
    environment:
      - DOCKER_SINK=docker.palantir.build/computetools
      - UBUNTU_URI=https://artifactory.palantir.build/artifactory/external-apt-ubuntu-ec2/

workflows:
  version: 2
  build:
    jobs:
      - build

  nightly:
    triggers:
      - schedule:
          cron: "30 7 * * *"
          filters:
            branches:
              only:
                - master
    jobs:
      - nightly
